close all;
clear variables;
path(pathdef); %clear all paths

SMSMain=figure('Name','Troika_SPT',...
    'Menubar','none',...
    'Units','Normalized',...
    'Position',[0 0 1 1],...
    'NumberTitle','off', ...
    'DoubleBuffer','on');   % turn off the flickering

[filename1, filepath1] = uigetfile({'*.tif','*.mptiff'});
[filename2, filepath2] = uigetfile({'*.tif','*.mptiff'});

addpath(filepath1);
addpath(filepath2); 
pos = imread(filename1);
spec = imread(filename2);

W = awt1d(spec);  %W = AWT(I) computes the A Trou Wavelet Transform of image I. Code in awt1d.m.
a_trous_transformed_spec = sum(W(:,:,7:end),3);
part_num = 0; % for frame_accepted.m & Map_2d.m

% GUI left top
fh1 = subplot(2,2,1);imagesc(pos); % set subplot(2,2,1)equals to fh1 for frame_accepted.m
% GUI right top
subplot(2,2,2); 
imagesc(a_trous_transformed_spec);

% origin point for UI buttons and intervals
anchor = [0.13 0.47 0.073 0.037];
ui_x_interval = 0.1;
ui_y_interval = 0.05;

%% Title and Date
% A title for this gui
uicontrol('Style','Text',...               
    'String','Landes&Link Research Group Spectra Fitting Program',...
    'Units','Normalized',...
    'Position',[0 0.95 0.3125 0.037],...
    'Tag','IP_Text','FontSize',16);

% Date
uicontrol('Style','Text',...                
    'String','Date',...
    'Units','Normalized',...
    'Position',[0.35 0.95 0.3125*0.1 0.037],... 
    'FontSize',16);

uicontrol('Style','Edit',...              
    'String','e.g. 210526',...
    'Units','Normalized',...
    'Position',[0.4 0.95 0.3125*0.3 0.037],...
    'Tag','date','FontSize',12);

%% First row of UI buttons

%Zoom In: turn on zoom mode
uicontrol('Style','PushButton',...           
    'String','Zoom Mode On',...
    'Units','Normalized',...
    'Position', anchor,...
    'Callback','zoom on',...
    'Tag','Zoom in','FontSize',12);

%Zoom Off: turn off zoom mode
uicontrol('Style','PushButton',...           
    'String','Zoom Mode Off',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval anchor(2) anchor(3) anchor(4)],...
    'Callback','zoom off',...
    'Tag','Zoom off','FontSize',12);

%Select a Particle
%call back to select_particle.m
uicontrol('Style','PushButton',...           
    'String','Select a Particle',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*2 anchor(2) anchor(3) anchor(4)],...
    'Callback','select_particle',...
    'Tag','Select a Particle','FontSize',12);

%Select BG
%call back to Select_BG.m
uicontrol('Style','PushButton',...           
    'String','Select BG',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*3 anchor(2) anchor(3) anchor(4)],...
    'Callback','Select_BG',...
    'Tag','Select_BG','FontSize',12);

%Check Images
%call back to Check_images.m
uicontrol('Style','PushButton',...          
    'String','Check Images',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*4 anchor(2) anchor(3) anchor(4)],...
    'Callback','Check_images',...
    'Tag','Check_images','FontSize',12);

%Fitting
%call back to single_frame.m
uicontrol('Style','PushButton',...          
    'String','Fitting',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*5 anchor(2) anchor(3) anchor(4)],...
    'Callback','single_frame',...
    'Tag','Fitting','FontSize',12);

%Particle Accepted
%call back to frame_accepted.m
uicontrol('Style','PushButton',...          
    'String','Particle Accepted',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*6 anchor(2) anchor(3) anchor(4)],...
    'Callback','frame_accepted',...
    'Tag','Frame Accepted','FontSize',12);

%Make Map
%call back to Map_2d.m
uicontrol('Style','PushButton',...          
    'String','Make Map',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*7 anchor(2) anchor(3) anchor(4)],...
    'Callback','Map_2d',...
    'Tag','2D Map','FontSize',12);

%% Second/Third row of UI buttons

%Save Figure
save_figure = uicontrol('Style','checkbox',...          
    'String','Save Figure',...
    'Units','Normalized',...
    'Position',[anchor(1) anchor(2)-ui_y_interval anchor(3) anchor(4)],...
    'FontSize',12, ...
    'Value', 0);

%Plot Data
plot_data = uicontrol('Style','checkbox',...          
    'String','Plot Data',...
    'Units','Normalized',...
    'Position',[anchor(1) anchor(2)-ui_y_interval*2 anchor(3) anchor(4)],...
    'FontSize',12, ...
    'Value', 1);

%Start Frame input
uicontrol('Style','Text',...                
    'String','Start Frame',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval anchor(2)-ui_y_interval*1.2 anchor(3) anchor(4)],... %*1.2 for centering
    'FontSize',12);

uicontrol('Style','Edit',...                
    'String','1',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*2 anchor(2)-ui_y_interval anchor(3) anchor(4)],...
    'Tag','sf','FontSize',12);

%End Frame input
uicontrol('Style','Text',...                
    'String','End Frame',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval anchor(2)-ui_y_interval*2.2 anchor(3) anchor(4)],... %*2.2 for centering
    'FontSize',12);

uicontrol('Style','Edit',...              
    'String','1',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*2 anchor(2)-ui_y_interval*2 anchor(3) anchor(4)],...
    'Tag','ef','FontSize',12);

%Power input
uicontrol('Style','Text',...                
    'String','Power',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*3 anchor(2)-ui_y_interval*1.2 anchor(3) anchor(4)],... %*1.2 for centering
    'FontSize',12);

uicontrol('Style','Edit',...                
    'String','High',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*4 anchor(2)-ui_y_interval anchor(3) anchor(4)],...
    'Tag','power','FontSize',12);

%Potential input
uicontrol('Style','Text',...                
    'String','Potential',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*3 anchor(2)-ui_y_interval*2.2 anchor(3) anchor(4)],... %*2.2 for centering
    'FontSize',12);

uicontrol('Style','Edit',...              
    'String','1',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*4 anchor(2)-ui_y_interval*2 anchor(3) anchor(4)],...
    'Tag','potential','FontSize',12);

%Stack Fitting
%call back to multi_frame.m
uicontrol('Style','PushButton',...          
    'String','Stack Fitting',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*5 anchor(2)-ui_y_interval*1.5 anchor(3) anchor(4)],...
    'Callback','multi_frame',...               
    'Tag','Stack Fitting','FontSize',12);

%Plot changes for one partcle in multi frames
%call back to 
uicontrol('Style','PushButton',...          
    'String','Plot Changes for one',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*6 anchor(2)-ui_y_interval anchor(3)*2.37 anchor(4)],...
    'Callback','AnalysisPlot1',...
    'FontSize',12);

%Plot changes for all particles in multi frames
%call back to 
uicontrol('Style','PushButton',...          
    'String','Plot Changes for all',...
    'Units','Normalized',...
    'Position',[anchor(1)+ui_x_interval*6 anchor(2)-ui_y_interval*2 anchor(3)*2.37 anchor(4)],...
    'Callback','AnalysisPlot2',...
    'FontSize',12);

